- name: Install certbot
  apt:
    name: python3-certbot-dns-{{ certbot_dns_provider }}

- name: Create secret directory
  file: 
    path: "/root/.secrets/certbot/"
    mode: 0600
    state: directory

- name: Copy API keys file
  template:
    src: "{{ certbot_dns_provider }}.ini"
    dest: "/root/.secrets/certbot/{{ certbot_dns_provider }}.ini"
    mode: 0600

- name: Create hook directories
  file:
    path: /etc/letsencrypt/{{ item }}
    mode: 0750
    owner: root
    group: root
    state: directory
  loop:
    - renewal-hooks
    - renewal-hooks/pre
    - renewal-hooks/post

- name: Check that the cert exists
  stat:
    path: "/etc/letsencrypt/live/{{ certbot_wildcard_domain }}/fullchain.pem"
  register: cert_result
  
- name: Generate Let's Encrypt cert if not exists (staging mode)
  shell: "certbot certonly --staging --dns-{{ certbot_dns_provider }} --dns-ovh-credentials /root/.secrets/certbot/{{ certbot_dns_provider }}.ini -d *.{{ certbot_wildcard_domain }} -m {{ certbot_mail }} --agree-tos -n"
  when: not cert_result.stat.exists and certbot_staging
  ignore_errors: yes

- name: Generate Let's Encrypt cert if not exists (production mode)
  shell: "certbot certonly --dns-{{ certbot_dns_provider }} --dns-ovh-credentials /root/.secrets/certbot/{{ certbot_dns_provider }}.ini -d *.{{ certbot_wildcard_domain }} -m {{ certbot_mail }} --agree-tos -n"
  when: not cert_result.stat.exists and not certbot_staging
  ignore_errors: yes

